# Generated by Django 4.1.7 on 2023-06-25 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_url', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'youtube_creator',
            },
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pk', models.CharField(max_length=64, unique=True)),
                ('channel_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnails', models.URLField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('play_time', models.CharField(max_length=8)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.creator')),
            ],
            options={
                'db_table': 'youtube',
            },
        ),
        migrations.CreateModel(
            name='Category_Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.category')),
                ('youtube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.youtube')),
            ],
            options={
                'db_table': 'category_youtube',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='youtube',
            field=models.ManyToManyField(through='youtube.Category_Youtube', to='youtube.youtube'),
        ),
        migrations.AddConstraint(
            model_name='youtube',
            constraint=models.UniqueConstraint(fields=('url_pk',), name='url_pk'),
        ),
    ]
