# Generated by Django 4.2.4 on 2023-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtubeingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='thumbnail_url',
            field=models.URLField(max_length=255),
        ),
    ]
