# Generated by Django 4.2.4 on 2023-08-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_creator_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='youtube',
        ),
        migrations.AddField(
            model_name='category',
            name='youtube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.youtube'),
        ),
    ]
