# Generated by Django 4.2.4 on 2023-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_category_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='youtube',
        ),
        migrations.AddField(
            model_name='category',
            name='youtube',
            field=models.ManyToManyField(related_name='category', through='youtube.Category_Youtube', to='youtube.youtube'),
        ),
    ]
