# Generated by Django 4.1.7 on 2023-06-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='is_vaild',
            new_name='is_valid',
        ),
    ]
