# Generated by Django 4.2.4 on 2023-08-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryingredients',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
