# Generated by Django 4.2.3 on 2023-07-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_ingredients_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='updated_at',
        ),
    ]
