# Generated by Django 4.2.2 on 2023-07-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_ingredients_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'search_category_ingredients',
            },
        ),
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_ingredients', to='search.categoryingredients'),
        ),
    ]
