# Generated by Django 4.2.4 on 2023-08-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_categoryingredients_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
