# Generated by Django 4.2.4 on 2023-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_ingredients_aligned_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='is_not_connected',
            field=models.BooleanField(default=False),
        ),
    ]
